name: Prod Release Pull Request

on:
  push:
    branches:
      - develop

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read template
        id: template
        uses: juliangruber/read-file-action@v1
        with:
          path: ./newfile

      - name: pull-request-action
        id: pull_request
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_BODY: ${{ steps.template.outputs.content }}

      - name: Test outputs
        run: |
          echo $template
