name: Prod Release Pull Request

on:
  push:
    branches:
      - develop

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read content of newfile
        shell: bash
        run: echo "template=$(cat newfile)" >> $GITHUB_ENV
        id: get_template

      - name: pull-request-action
        id: pull_request
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_BODY: $template

      - name: Test outputs
        run: |
          echo $template
